### ISSUE TITLE
CMake fails

### ISSUE THREAD

**Issue by liyangliu** [mahyarnajibi/SNIPER#13]
Hello, @mahyarnajibi, I am new to mxnet and when I run the cmake command, it turns out:

-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMake version '3.11.4' using generator 'Unix Makefiles'
-- The CUDA compiler identification is NVIDIA 8.0.26
-- Check for working CUDA compiler: /usr/local/cuda-8.0/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda-8.0/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Performing Test SUPPORT_CXX11
-- Performing Test SUPPORT_CXX11 - Success
-- Performing Test SUPPORT_CXX0X
-- Performing Test SUPPORT_CXX0X - Success
-- Performing Test SUPPORT_MSSE2
-- Performing Test SUPPORT_MSSE2 - Success
CMake Deprecation Warning at 3rdparty/mkldnn/CMakeLists.txt:21 (cmake_policy):
  The OLD behavior for policy CMP0048 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

CMake Deprecation Warning at 3rdparty/mkldnn/CMakeLists.txt:22 (cmake_policy):
  The OLD behavior for policy CMP0054 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

-- CMAKE_BUILD_TYPE is unset, defaulting to Release
-- Detecting Intel(R) MKL: trying mklml_intel
-- Detecting Intel(R) MKL: trying mklml
-- Detecting Intel(R) MKL: trying mkl_rt
CMake Warning at 3rdparty/mkldnn/cmake/MKL.cmake:178 (message):
  Intel(R) MKL not found.  Some performance features may not be available.
  Please run scripts/prepare_mkl.sh to download a minimal set of libraries or
  get a full version from https://software.intel.com/en-us/intel-mkl
Call Stack (most recent call first):
  3rdparty/mkldnn/cmake/OpenMP.cmake:25 (include)
  3rdparty/mkldnn/CMakeLists.txt:57 (include)

-- Found OpenMP_C: -fopenmp (found version "3.1") 
-- Found OpenMP_CXX: -fopenmp (found version "3.1") 
-- Found OpenMP: TRUE (found version "3.1")  
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- VTune profiling environment is unset
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Could NOT find MKL (missing: MKL_INCLUDE_DIR MKLML_GNU_LIBRARY MKLDNN_LIBRARY) 
--  MKL not found
-- Found CUDA: /usr/local/cuda-8.0 (found version "8.0") 
-- Could NOT find MKL (missing: MKL_INCLUDE_DIR MKLML_GNU_LIBRARY MKLDNN_LIBRARY) 
-- Found OpenBLAS libraries: /usr/lib/libopenblas.so
-- Found OpenBLAS include: /usr/include
-- Could NOT find Gperftools (missing: GPERFTOOLS_LIBRARIES GPERFTOOLS_INCLUDE_DIR) 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- Could NOT find Jemalloc (missing: JEMALLOC_LIBRARY JEMALLOC_INCLUDE_DIR) 
--  OpenCV_LIBS=opencv_core;opencv_highgui;opencv_imgproc
-- OpenCV found (/usr/share/OpenCV)
-- Found OpenMP_C: -fopenmp  
-- Found OpenMP_CXX: -fopenmp  
-- Found OpenMP: TRUE   
CMake Error at SNIPER/SNIPER-mxnet/build/3rdparty/openmp/runtime/CMakeFiles/CMakeTmp/CMakeLists.txt:3 (project):
  Generator

    Unix Makefiles

  does not support toolset specification, but toolset

    cuda=,host=x64

  was specified.

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error at 3rdparty/openmp/runtime/cmake/LibompGetArchitecture.cmake:57 (try_run):
  Failed to configure test project build system.
Call Stack (most recent call first):
  3rdparty/openmp/runtime/CMakeLists.txt:40 (libomp_get_architecture)

-- Configuring incomplete, errors occurred!

Would you please be so kind as to help me out? Thanks.

**Comment by jwnsu** [comment]
You can ignore build instruction in this project's readme, instead follow incubator-mxnet instruction to build: https://mxnet.apache.org/install/index.html, which does not have cmake step.

**Comment by liyangliu** [comment]
Thanks, @jwnsu, I have installed mxnet successfully, but I can't compile NMS, when I run compile.sh, it turns out: 
**g++: error: unrecognized command line option ‘-R’**
so I can't run demo.py which says:
**ModuleNotFoundError: No module named 'cpu_nms'**
In other projects like py-faster-rcnn I have compiled NMS successfully.

Have you met this problem? Thanks.

**Comment by mahyarnajibi** [comment]
I cannot reproduce the problem. Does changing the ```-R``` flag as described in https://github.com/rbgirshick/py-faster-rcnn/issues/706 solves it?

**Comment by liyangliu** [comment]
Yes @mahyarnajibi, I followed rbgirshick/py-faster-rcnn#706 and change the -R flag and get the compiled .so file, but it is named as **cpu_nms.cpython-36m-x86_64-linux-gnu.so**, is it normal?

**Comment by mahyarnajibi** [comment]
Usually it should create a shared object called ```cpu_nms.so```. Are you able to run the ```demo.py```? If not maybe you can create a symbolic link named ```cpu_nms.so``` and pointing to your file in the *lib/nms* directory.

**Comment by liyangliu** [comment]
@mahyarnajibi, No I can't run demo.py, and the error still occurs after I created the symbolic link pointing to    the compiled .so file. I noticed the error points to this line:

Traceback (most recent call last):
  File "demo.py", line 16, in <module>
    from iterators.MNIteratorTest import MNIteratorTest
  File "lib/iterators/MNIteratorTest.py", line 3, in <module>
    from data_utils.data_workers import im_worker
  File "lib/data_utils/data_workers.py", line 10, in <module>
    from nms.nms import nms_wrapper
  File "lib/nms/nms.py", line 3, in <module>
    **from cpu_nms import cpu_nms, cpu_soft_nms**
ModuleNotFoundError: No module named 'cpu_nms'

But I can't find cpu_nms.py in lib/nms but only cpu_nms.pyx, is this normal?

BTW is it OK that I installed mxnet just with **pip install mxnet-cu80**?

**Comment by mahyarnajibi** [comment]
What is your g++ version? Are you using conda and if so what is the version? 

Yes, .pyx files are converted to .c files by cython and eventually to .so files by a C compiler which can be imported in python, so it is the only file you need.

Nope, unfortunately pip won't work as we have custom CUDA/C++ layers which are not yet included in the standard MXNet library. You need to compile the provided ```SNIPER-mxnet``` repository with the ```make``` command as described in the README but post here if you face any problems.

**Comment by liyangliu** [comment]
Hi, @mahyarnajibi, my g++ version is 4.8.4 and conda is 4.4.7

I tried to compile SNIPER-mxnet according to your README, but error occurs as:
**error: ‘CUDA_R_32I’ was not declared in this scope**

**Comment by liyangliu** [comment]
@mahyarnajibi BTW, my CUDA version is 8.0.26

**Comment by hyxu2006** [comment]
@liyangliu I encountered the same error you had and I am able to solve it. Did you use any virtualenv to compile and generate the file? In my case, I use virtualenv to run the mxnet and the original virtualenv python version is 3.5. I changed it to version 2.7 and re-compile: bash scripts/compile.sh.
I think current nms code may not work properly with python 3.5. 

After that I am able to run the demo.py. Hope this would be helpful. 
@mahyarnajibi have you tested the code on other python version?

**Comment by liyangliu** [comment]
@hyxu2006, now I can't even compile SNIPER-mxnet successfully, what cuda version are you using? Thanks.

**Comment by liyangliu** [comment]
Thanks @hyxu2006 , I compiled mxnet with "make -j 4 USE_CUDA=1 USE_CUDA_PATH=/usr/local/cuda USE_CUDNN=1" successfully, and by using Python 2.7 I can compile NMS now.

**Comment by liyangliu** [comment]
Also，I have to change CUDA_R_32I to CUDA_R_32F, did you do this @hyxu2006 ?

**Comment by hyxu2006** [comment]
Hi @liyangliu I did not change this.

**Comment by Andrea-Chang** [comment]
Hi @liyangliu , @hyxu2006 
I successfully compiled SNIPER-mxnet,
(Ubuntu18.04, CUDA10.0, Python2.7, g++/gcc 5.5.0)
But, when I compile: bash scripts/compile.sh
I got the following error msg:

> Compiling NMS module...
running build_ext
skipping 'cpu_nms.c' Cython extension (up-to-date)
building 'cpu_nms' extension
p++6 -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/test/anaconda3/envs/SNIPER-py27/lib/python2.7/site-packages/numpy/core/include -I/home/test/anaconda3/envs/SNIPER-py27/include/python2.7 -c cpu_nms.c -o build/temp.linux-x86_64-2.7/cpu_nms.o -Wno-cpp -Wno-unused-function
unable to execute 'p++6': No such file or directory
error: command 'p++6' failed with exit status 1
Compiling bbox module...
running build_ext
skipping 'bbox.c' Cython extension (up-to-date)
building 'bbox' extension
p++6 -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/test/anaconda3/envs/SNIPER-py27/lib/python2.7/site-packages/numpy/core/include -I/home/test/anaconda3/envs/SNIPER-py27/include/python2.7 -c bbox.c -o build/temp.linux-x86_64-2.7/bbox.o -Wno-cpp -Wno-unused-function
unable to execute 'p++6': No such file or directory
error: command 'p++6' failed with exit status 1
Compiling chips module...
running build_ext
skipping 'chips.cpp' Cython extension (up-to-date)
building 'chips' extension
p++6 -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/test/anaconda3/envs/SNIPER-py27/lib/python2.7/site-packages/numpy/core/include -I/home/test/anaconda3/envs/SNIPER-py27/include/python2.7 -c chips.cpp -o build/temp.linux-x86_64-2.7/chips.o
unable to execute 'p++6': No such file or directory
error: command 'p++6' failed with exit status 1
Compiling coco api...
running build_ext
building '_mask' extension
p++6 -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/test/anaconda3/envs/SNIPER-py27/lib/python2.7/site-packages/numpy/core/include -I/home/test/anaconda3/envs/SNIPER-py27/include/python2.7 -c _mask.c -o build/temp.linux-x86_64-2.7/_mask.o -Wno-cpp -Wno-unused-function -std=c99
unable to execute 'p++6': No such file or directory
error: command 'p++6' failed with exit status 1
All Done!

have you ever met this error?

kindly help, thanks.
