### ISSUE TITLE
AttributeError: type object '_mask.RLEs' has no attribute '__reduce_cython__'

### ISSUE THREAD

**Issue by captaincj** [mahyarnajibi/SNIPER#135]
I ran into the error when i tried to train SNIPER using python2. It is just fine when runing demo.py.
This is the traceback:
Traceback (most recent call last):
  File "main_train.py", line 24, in <module>
    from lib.data_utils.load_data import load_proposal_roidb, merge_roidb, filter_roidb
  File "/home/qinlikun/SNIPER/lib/data_utils/load_data.py", line 11, in <module>
    from lib.dataset import *
  File "/home/qinlikun/SNIPER/lib/dataset/__init__.py", line 3, in <module>
    from coco import coco
  File "/home/qinlikun/SNIPER/lib/dataset/coco.py", line 16, in <module>
    from mask.mask_voc2coco import mask_voc2coco
  File "lib/mask/mask_voc2coco.py", line 10, in <module>
    from dataset.pycocotools.mask import encode as encodeMask_c
  File "lib/dataset/__init__.py", line 3, in <module>
    from coco import coco
  File "lib/dataset/coco.py", line 14, in <module>
    from .pycocotools.coco import COCO
  File "lib/dataset/pycocotools/coco.py", line 58, in <module>
    import mask
  File "lib/dataset/pycocotools/mask.py", line 3, in <module>
    import _mask as _mask
  File "_mask.pyx", line 56, in init _mask
AttributeError: type object '_mask.RLEs' has no attribute '__reduce_cython__'

# packages in environment at /home/qinlikun/.conda/envs/sniper:
#
# Name                    Version                   Build  Channel
argparse                  1.4.0                     <pip>
backports.functools-lru-cache 1.5                       <pip>
ca-certificates           2019.1.23                     0
certifi                   2019.3.9                 py27_0
cloudpickle               1.0.0                     <pip>
cycler                    0.10.0                    <pip>
Cython                    0.29.7                    <pip>
dask                      1.2.2                     <pip>
decorator                 4.4.0                     <pip>
easydict                  1.9                       <pip>
futures                   3.2.0                     <pip>
kiwisolver                1.1.0                     <pip>
libedit                   3.1.20181209         hc058e9b_0
libffi                    3.2.1                hd88cf55_4
libgcc-ng                 8.2.0                hdf63c60_1
libstdcxx-ng              8.2.0                hdf63c60_1
matplotlib                2.2.4                     <pip>
ncurses                   6.1                  he6710b0_1
networkx                  2.2                       <pip>
numpy                     1.16.3                    <pip>
opencv-python             4.1.0.25                  <pip>
openssl                   1.1.1b               h7b6447c_1
Pillow                    6.0.0                     <pip>
pip                       19.1.1                   py27_0
protobuf                  3.7.1                     <pip>
pyparsing                 2.4.0                     <pip>
python                    2.7.16               h9bab390_0
python-dateutil           2.8.0                     <pip>
pytz                      2019.1                    <pip>
PyWavelets                1.0.3                     <pip>
PyYAML                    5.1                       <pip>
readline                  7.0                  h7b6447c_5
scikit-image              0.14.2                    <pip>
scipy                     1.2.1                     <pip>
setuptools                41.0.1                   py27_0
six                       1.12.0                    <pip>
sqlite                    3.28.0               h7b6447c_0
subprocess32              3.5.3                     <pip>
tk                        8.6.8                hbc83047_0
toolz                     0.9.0                     <pip>
tqdm                      4.32.1                    <pip>
wheel                     0.33.2                   py27_0
zlib                      1.2.11               h7b6447c_3

**Comment by DreamerDoReMi** [comment]
Excume me, have you figured out this problem?
