### ISSUE TITLE
no nancumprod while main_train.py

### ISSUE THREAD

**Issue by aimhabo** [mahyarnajibi/SNIPER#143]
after [installed](https://github.com/mahyarnajibi/SNIPER#install) in /usr/bin/python (and I ban anaconda already), demo.py is ok, results show good.
![Screenshot from 2019-06-10 19-00-18](https://user-images.githubusercontent.com/12708080/59191408-14bed100-8bb2-11e9-8adf-505e93dad524.png)

but while I try to train my coco-style dataset. It comes out:

> xx/SNIPER$ python main_train.py 
> Traceback (most recent call last):
>   File "main_train.py", line 24, in <module>
>     from data_utils.load_data import load_proposal_roidb, merge_roidb, filter_roidb
>   File "lib/data_utils/load_data.py", line 11, in <module>
>     from dataset import *
>   File "lib/dataset/__init__.py", line 3, in <module>
>     from coco import coco
>   File "lib/dataset/coco.py", line 14, in <module>
>     from .pycocotools.coco import COCO
>   File "lib/dataset/pycocotools/coco.py", line 54, in <module>
>     from skimage.draw import polygon
>   File "/usr/local/lib/python2.7/dist-packages/skimage/__init__.py", line 167, in <module>
>     from .util.dtype import (img_as_float32,
>   File "/usr/local/lib/python2.7/dist-packages/skimage/util/__init__.py", line 6, in <module>
>     from .apply_parallel import apply_parallel
>   File "/usr/local/lib/python2.7/dist-packages/skimage/util/apply_parallel.py", line 8, in <module>
>     import dask.array as da
>   File "/usr/local/lib/python2.7/dist-packages/dask/array/__init__.py", line 5, in <module>
>     from .core import (Array, block, concatenate, stack, from_array, store,
>   File "/usr/local/lib/python2.7/dist-packages/dask/array/core.py", line 29, in <module>
>     from . import chunk
>   File "/usr/local/lib/python2.7/dist-packages/dask/array/chunk.py", line 73, in <module>
>     nancumprod = npcompat.nancumprod
> AttributeError: 'module' object has no attribute 'nancumprod'
> 

I had have numpy==1.16.4, is it too high? I downgrade it to 1.13.3(min version for scipy 1.3.0), it still comes out.

![Screenshot from 2019-06-10 19-17-50](https://user-images.githubusercontent.com/12708080/59192271-78e29480-8bb4-11e9-9436-4cf1c77d4215.png)

**Comment by aimhabo** [comment]
pip2 install numpy==1.16.1 --user 
√
