### ISSUE TITLE
arg_shape_dict doesn't contain key 'stage4_unit1_offset_weight'

### ISSUE THREAD

**Issue by ash1995** [mahyarnajibi/SNIPER#146]
I tried training the SNIPER network on my own dataset and on the COCO dataset and encountered this error. 

Traceback (most recent call last):
  File "main_train.py", line 117, in <module>
    sym_inst.init_weight_rpn(config, arg_params, aux_params)
  File "/sniper/symbols/faster/resnet_mx_101_e2e_mask.py", line 643, in init_weight_rpn
    arg_params['stage4_unit1_offset_weight'] = mx.nd.zeros(shape=self.arg_shape_dict['stage4_unit1_offset_weight'])
KeyError: 'stage4_unit1_offset_weight'

So the arg_shape_dict doesn't contain the key 'stage4_unit1_offset_weight'. In fact the arg_params dict has 332 keys and arg_shape_dict has only 288 keys which I'm assuming shouldn't be the case.

**Comment by ash1995** [comment]
My bad. I was using the incorrect symbol graph.
