### ISSUE TITLE
Error when training on a new dataset based on config of pascal?

### ISSUE THREAD

**Issue by duynn912** [mahyarnajibi/SNIPER#157]
I successfully trained pascal with this config "sniper_res101_e2e_pascal_voc.yml" and I tried to train a new dataset with this but I have a problem as follow:
Traceback (most recent call last):
  File "main_train.py", line 145, in <module>
    epoch_end_callback=epoch_end_callback, arg_params=arg_params, aux_params=aux_params)
  File "SNIPER-mxnet/python/mxnet/module/base_module.py", line 520, in fit
    self.update_metric(eval_metric, data_batch.label)
  File "SNIPER-mxnet/python/mxnet/module/module.py", line 757, in update_metric
    self._exec_group.update_metric(eval_metric, labels)
  File "SNIPER-mxnet/python/mxnet/module/executor_group.py", line 616, in update_metric
    eval_metric.update_dict(labels_, preds)
  File "SNIPER-mxnet/python/mxnet/metric.py", line 304, in update_dict
    metric.update_dict(labels, preds)
  File "SNIPER-mxnet/python/mxnet/metric.py", line 132, in update_dict
    self.update(label, pred)
  File "lib/train_utils/metric.py", line 200, in update
    cls = pred[keep_inds, label]
IndexError: index 144 is out of bounds for axis 1 with size 81

Although I have changed the NUM_CLASSES  and paths to dataset in "sniper_res101_e2e_pascal_voc.yml", the name of classes in pascal_voc.py. My dataset have 200 classes. So do I need to change anything in other files for training on a new dataset. I also trained with the command to generate proposals but after 2 epoch for proposals, it suffers from the above problem.
 If someone have a glimpse of this note, please help me out. Thank you so much!

**Comment by ten1er** [comment]
Hi, I missed similar problem, have you solved it ?
