### ISSUE TITLE
 name 'resnet_mx_50_e2e' is not defined

### ISSUE THREAD

**Issue by aimhabo** [mahyarnajibi/SNIPER#161]
> Initializing the model...
> Traceback (most recent call last):
>   File "main_train.py", line 90, in <module>
>     sym_inst = eval('{}.{}'.format(config.symbol, config.symbol))(n_proposals=500, momentum=args.momentum)
>   File "<string>", line 1, in <module>
> NameError: name 'resnet_mx_50_e2e' is not defined
> configs/faster/default_configs.py:171: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
>   exp_config = edict(yaml.load(f))
> Extracting proposals on train2014 for negative chip mining...
> ./SNIPER/configs/faster/default_configs.py:171: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
>   exp_config = edict(yaml.load(f))
> loading annotations into memory...
> Done (t=2.66s)
> creating index...
> index created!
> 

Current version is seem like not fit with resnet-50, would you like to provide one?

**Comment by aimhabo** [comment]
done with adding 'import resnet_mx_50_e2e' to ./symbols/faster/__init__.py
