### ISSUE TITLE
KeyError: 'conv_new_2_weight'

### ISSUE THREAD

**Issue by szr712** [mahyarnajibi/SNIPER#175]
I tried training the SNIPER network on my own dataset and on the VOC dataset and encountered this error:

/home/pwh/FWWB/SNIPER-master/configs/faster/default_configs.py:181: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  exp_config = edict(yaml.load(f))
num_images 1286
PASCALVOC_2007_trainval gt roidb loaded from ./data/cache/PASCALVOC_2007_trainval_gt_roidb.pkl
appending ground truth annotations
Reading cached proposals after ***NMS**** from data/proposals/PASCALVOC_2007_trainval_rpn_after_nms.pkl
Done!
append flipped images to roidb
filtered 24 roidb entries: 2572 -> 2548
add bounding box regression targets
bbox target means:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[0. 0. 0. 0.]
bbox target stdevs:
[[0.1 0.1 0.2 0.2]
 [0.1 0.1 0.2 0.2]]
[0.1 0.1 0.2 0.2]
Creating Iterator with 2548 Images
Total number of extracted chips: 11472
Done!
The Iterator has 11472 samples!
Initializing the model...
Traceback (most recent call last):
  File "main_train.py", line 103, in <module>
    sym_inst.init_weight_rcnn(config, arg_params, aux_params)
  File "/home/pwh/FWWB/SNIPER-master/symbols/faster/resnet_mx_101_e2e.py", line 468, in init_weight_rcnn
    arg_params['conv_new_2_weight'] = mx.random.normal(0, 0.01, shape=self.arg_shape_dict['conv_new_2_weight'])
KeyError: 'conv_new_2_weight'

**Comment by szr712** [comment]
The repository must be cloned by git. Otherwise, it is easy to get the above error.
