### ISSUE TITLE
How to train this on a new dataset ?

### ISSUE THREAD

**Issue by suvojit-0x55aa** [mahyarnajibi/SNIPER#18]
I'm using a custom dataset. But it's asking for RPN weights, is there any way to bypass that. If I load the weights, it failing with the following error:
```
Loading data/proposals/voc_2007_trainval_rpn.pkl....
Done!
Applying NMS...
Traceback (most recent call last):
  File "main_train.py", line 59, in <module>
    for image_set in image_sets]
  File "lib/data_utils/load_data.py", line 32, in load_proposal_roidb
    roidb = eval('imdb.' + proposal + '_roidb')(roidb, append_gt,proposal_path=proposal_path)
  File "lib/dataset/imdb.py", line 139, in rpn_roidb
    rpn_roidb = self.load_rpn_roidb(gt_roidb,proposal_path)
  File "lib/dataset/imdb.py", line 126, in load_rpn_roidb
    box_list, mapping_list = self.load_rpn_data(proposal_path)
  File "lib/dataset/imdb.py", line 109, in load_rpn_data
    keeps = p.map(nmsp, ttboxes)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
IndexError: too many indices for array
```

**Comment by bharatsingh430** [comment]
this will be resolved soon, we are aware of the issue.

**Comment by bharatsingh430** [comment]
In the meantime you can use the openimages branch if you don’t have many small objects but it doesn’t include negative sampling. Images are expected to be around 1000x768 so only downsampling is done.

**Comment by Ram124** [comment]
@bharatsingh430 If i need to train on my own dataset of 15000 images.
What changes should i do to detect 2 different classes?
Is this repo compatible with pascal format dataset?
Where am i supposed to give the batch size for training? 
I have many images, so i need larger batch size. so. I am using aws p2.xlarge instance. So what is the appropriate batch size??

**Comment by suvojit-0x55aa** [comment]
@bharatsingh430 thanks for the clarification. I've a dataset of high resolution images but the objects are small. Will using the openimages branch be effective ?

**Comment by bharatsingh430** [comment]
Yes, it will work (but little worse). the end to end version will be put out soon after some testing

**Comment by mahyarnajibi** [comment]
Hi @suvojit-0x55aa,
Commit 8711340 addresses this issue by adding an option to the ```master``` branch which removes the need for proposals.
Pull the SNIPER ```master``` branch and then you should be able to train on your new dataset by running ```python main_train.py --set TRAIN.USE_NEG_CHIPS False```.
In the near future, the option for training on new datasets with negative chip mining would be also added to the ```master```.
Hope it helps!

**Comment by xiaomengyc** [comment]
Hi  @mahyarnajibi ,
I till got the error message `AssertionError: rpn data not found at data/proposals/COCO_train2017_rpn.pkl` using the command `python main_train.py --set TRAIN.USE_NEG_CHIPS False`.  
Can you tell me how to generate this `*_rpn.pkl` file for a new dataset ?

Thanks a lot!

**Comment by mahyarnajibi** [comment]
Did you pull the master after commit 8711340? Just to make sure can you manually set the ```TRAIN.USE_NEG_CHIPS``` to ```False``` in ```configs/faster/default_configs.py```. The script for  training on new datasets with negative chip mining would be added in the next couple of days but right now you should be able to train without the need for the rpn data.

**Comment by xiaomengyc** [comment]
Hi  @mahyarnajibi ,

Thank you very much!  After pulling the latest files, the rpn problem has gone. 
However, I run into a kind of `simple_bind error` :
`Traceback (most recent call last):
  File "main_train.py", line 132, in <module>
    epoch_end_callback=epoch_end_callback, arg_params=arg_params, aux_params=aux_params)
  File "SNIPER-mxnet/python/mxnet/module/base_module.py", line 484, in fit
    for_training=True, force_rebind=force_rebind)
  File "SNIPER-mxnet/python/mxnet/module/module.py", line 430, in bind
    state_names=self._state_names)
  File "SNIPER-mxnet/python/mxnet/module/executor_group.py", line 265, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "SNIPER-mxnet/python/mxnet/module/executor_group.py", line 361, in bind_exec
    shared_group))
  File "SNIPER-mxnet/python/mxnet/module/executor_group.py", line 639, in _bind_ith_exec
    shared_buffer=shared_data_arrays, **input_shapes)
  File "SNIPER-mxnet/python/mxnet/symbol/symbol.py", line 1524, in simple_bind
    raise RuntimeError(error_msg)
RuntimeError: simple_bind error. Arguments:
bbox_target: (3, 84L, 32L, 32L)
im_info: (3, 3L)
valid_ranges: (3, 2L)
label: (3, 21504L)
gt_boxes: (3, 100L, 5L)
bbox_weight: (3, 84L, 32L, 32L)
data: (3, 3L, 512L, 512L)
[14:19:01] src/storage/storage.cc:65: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: invalid`

I have made the following changes 
`BATCH_IMAGES: 3
NUM_PROCESS: 8
NUM_THREAD: 2
`
so, I guess it should not be an 'out of memory' problem, as I have three K40c specified by `CUDA_VISIBLE_DEVICES`.

Do you have any idea how to fix this problem?

Thanks a lot!

**Comment by xiaomengyc** [comment]
@mahyarnajibi Thank you! It works very well now!

**Comment by suvojit-0x55aa** [comment]
Thanks @mahyarnajibi @bharatsingh430 for the update. I'm trying to run the network with the new configs but i'm running into following error on a Tesla P100: `CUDA error: too many resources requested for launch`. Can you give me a pointer on what maybe happening ?

**Comment by ddt2014** [comment]
@suvojit-0x55aa hi  have you solved this problem?

**Comment by suvojit-0x55aa** [comment]
@ddt2014 no I haven't

**Comment by pengyuan101** [comment]
have you added the code of training on new datasets with negative chip mining ?

> Did you pull the master after commit [8711340](https://github.com/mahyarnajibi/SNIPER/commit/87113401521512ecaa866cc6a6052a640531daa6)? Just to make sure can you manually set the `TRAIN.USE_NEG_CHIPS` to `False` in `configs/faster/default_configs.py`. The script for training on new datasets with negative chip mining would be added in the next couple of days but right now you should be able to train without the need for the rpn data.
