### ISSUE TITLE
error when training my own dataset

### ISSUE THREAD

**Issue by rmfckaka** [mahyarnajibi/SNIPER#31]
`loading annotations into memory...
Done (t=0.11s)
creating index...
index created!
num_images 8100
COCO_train2014 gt roidb loaded from ./data/cache/COCO_train2014_gt_roidb.pkl
append flipped images to roidb
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
num_images 900
COCO_val2014 gt roidb loaded from ./data/cache/COCO_val2014_gt_roidb.pkl
append flipped images to roidb
filtered 0 roidb entries: 18000 -> 18000
add bounding box regression targets
bbox target means:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[0. 0. 0. 0.]
bbox target stdevs:
[[0.1 0.1 0.2 0.2]
 [0.1 0.1 0.2 0.2]]
[0.1 0.1 0.2 0.2]
Creating Iterator with 18000 Images
Total number of extracted chips: 30025
Done!
Traceback (most recent call last):
  File "main_train.py", line 78, in <module>
    threads=config.TRAIN.NUM_THREAD, pad_rois_to=400)
  File "lib/iterators/MNIteratorE2E.py", line 32, in __init__
    super(MNIteratorE2E, self).__init__(roidb, config, batch_size, threads, nGPUs, pad_rois_to, False)
  File "lib/iterators/MNIteratorBase.py", line 33, in __init__
    self.get_batch()
  File "lib/iterators/MNIteratorE2E.py", line 100, in get_batch
    self.batch = self._get_batch()
  File "lib/iterators/MNIteratorE2E.py", line 195, in _get_batch
    processed_list = processed_list.get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
TypeError: 'NoneType' object has no attribute '__getitem__'`

could you help me to fix it?

**Comment by rmfckaka** [comment]
and i want to know how to train in voc2007

**Comment by rmfckaka** [comment]
I changed thr params in the yml:
`  NUM_PROCESS: 8
  NUM_THREAD: 4`

**Comment by radu-diaconescu13** [comment]
Hey. So it just worked after changing the params? I'm trying to change these values but nothing is happening, but it still doesnt work :(

**Comment by jjprincess** [comment]
> and i want to know how to train in voc2007

Hi. Did you success to train on VOC2007 ?

**Comment by rmfckaka** [comment]
> > and i want to know how to train in voc2007
> 
> Hi. Did you success to train on VOC2007 ?

yes, but i'm sorry that i can't find the code now.

**Comment by jjprincess** [comment]
> > > and i want to know how to train in voc2007
> > 
> > 
> > Hi. Did you success to train on VOC2007 ?
> 
> yes, but i'm sorry that i can't find the code now.

Okay, how about the performance? Waiting for your reply.

**Comment by rmfckaka** [comment]
similar to deformable network,but more efficient on my dataset.

**Comment by jjprincess** [comment]
> similar to deformable network,but more efficient in my dataset.

Thanks for your reply

**Comment by withmch** [comment]
Has someone solved the problem？Now I also encounter the same issue. Hope have a useful answer.

**Comment by heshuting555** [comment]
Could you tell me how to solve the problems, I also encounter the same issue. Waiting for your reply.Thank you for your help.
