### ISSUE TITLE
Can not train on new dataset

### ISSUE THREAD

**Issue by radu-diaconescu13** [mahyarnajibi/SNIPER#47]
Hello,

First of all thank you for putting the code here on github so we can all use and experiment with it.
I am trying to train on my own dataset,but I am having a little bit of trouble.
More specifically, I have  this error:
File "lib/iterators/MNIteratorE2E.py", line 194, in _get_batch
    processed_list = processed_list.get()
File "/home/radud/anaconda3/envs/mxnetpy2/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
TypeError: 'NoneType' object has no attribute '__getitem__'

Any help would be appreciated.
Thank you.

**Comment by JeasonUESTC** [comment]
@cubeFUN  If I train my own data set, should I name the image exactly the same format as COCO, or is there anything else I need to pay attention to?The generated COCO format data set can be trained in other platforms, but here the error has been reported as:
Traceback (most recent call last):
  File "main_train.py", line 82, in <module>
    threads=config.TRAIN.NUM_THREAD, pad_rois_to=400)
  File "lib/iterators/MNIteratorE2E.py", line 36, in __init__
    super(MNIteratorE2E, self).__init__(roidb, config, batch_size, threads, nGPUs, pad_rois_to, False)
  File "lib/iterators/MNIteratorBase.py", line 33, in __init__
    self.get_batch()
  File "lib/iterators/MNIteratorE2E.py", line 105, in get_batch
    self.batch = self._get_batch()
  File "lib/iterators/MNIteratorE2E.py", line 193, in _get_batch
    processed_list = processed_list.get()
  File "/root/miniconda2/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
TypeError: 'NoneType' object has no attribute '__getitem__'
