### ISSUE TITLE
KeyError: 'area'

### ISSUE THREAD

**Issue by lzh19961031** [mahyarnajibi/SNIPER#55]
Traceback (most recent call last):
  File "main_train.py", line 64, in <module>
    for image_set in image_sets]
  File "lib/data_utils/load_data.py", line 29, in load_proposal_roidb
    roidb = imdb.gt_roidb()
  File "lib/dataset/coco.py", line 135, in gt_roidb
    roientry,flag = self._load_coco_annotation(index)
  File "lib/dataset/coco.py", line 192, in _load_coco_annotation
    if obj['area'] > 0 and x2 >= x1 and y2 >= y1:
KeyError: 'area'

Who have met the same question?Please help me, thanks!!

**Comment by jiang-310** [comment]
Did you solve the problem? I had the same problem
