### ISSUE TITLE
could not broadcast input array from shape (101,5) into shape (100,5)

### ISSUE THREAD

**Issue by jliangqiu** [mahyarnajibi/SNIPER#60]
[10:03:52] src/kvstore/././comm.h:628: only 0 out of 2 GPU pairs are enabled direct access. It may affect the perfoet MXNET_ENABLE_GPU_P2P=0 to turn it off
[10:03:52] src/kvstore/././comm.h:637: ..
[10:03:52] src/kvstore/././comm.h:637: ..
[10:03:52] src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:107: Running performance tests to find the best convolutio can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
Exception in thread Thread-15:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "lib/iterators/PrefetchingIter.py", line 64, in prefetch_func
    self.next_batch[i] = self.iters[i].next()
  File "lib/iterators/MNIteratorBase.py", line 90, in next
    if self.iter_next():
  File "lib/iterators/MNIteratorBase.py", line 87, in iter_next
    return self.get_batch()
  File "lib/iterators/MNIteratorE2E.py", line 99, in get_batch
    self.batch = self._get_batch()
  File "lib/iterators/MNIteratorE2E.py", line 171, in _get_batch
    all_labels = self.pool.map(self.anchor_worker.worker, worker_data)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
ValueError: could not broadcast input array from shape (101,5) into shape (100,5)

**Comment by henrylee2570** [comment]
You can check if there are more than 100 gt boxes within a chip (you'll need to change the code to make it work if so)

**Comment by jliangqiu** [comment]
@henrylee2570 thank you

**Comment by YgRen** [comment]
@jliangqiu can you tell me how to change the code for this errror? Thx!

**Comment by aimhabo** [comment]
@henrylee2570 I have more than 100 objects in a chip, where could I change the limit?

**Comment by aimhabo** [comment]
This is about the number of labels, search for "100,"( or "100,5")  about reading the label box or matching the label, all that should be changed to "the maximum number of labels in the picture"

**Comment by lt1103725556** [comment]
@aimhabo could you please describe it in more detail? such as how can i find the code to change. my error info is "ValueError: could not broadcast input array from shape (106,5) into shape (100,5)".
