### ISSUE TITLE
SNIPER performace is not satisfying when porting to other dataset

### ISSUE THREAD

**Issue by kouhinn** [mahyarnajibi/SNIPER#74]
Thanks for open the SNIPER code.
Have yet selected SNIPER to add on my base model for another dataset. But I  only get 2-3 points improvement for mAP0.75, which is not satisfying.

So firstly I wonder if @mahyarnajibi  or anyone can confirm whether I have done the correct main change points or not.

Changes as following:
1st.The original image size is 1280*712, I have set the valid range ([-1, 70], [60, 180], [170, -1] ) and scales([ 3.0, 1.667, 1280.0]), and use the same code to generated chips.

2nd.I have made anchors on chips and set those  anchors with gt_box not in the valid range to -1 which is not being trained later.

Negative samples are not used currently, am I missing any important changes for SNIPER?

**Comment by RajathSwaroop** [comment]
@kouhinn  did you get the demo of SNIPER to work? Can you please post the build process if you got it to work. I am having issue with import errors trying to run demo.py

I keep getting these errors when I run demo.py
Traceback (most recent call last):
  File "demo.py", line 118, in <module>
    main()
  File "demo.py", line 79, in main
    sym = sym_inst.get_symbol_rcnn(config, is_train=False)
  File "/home/rajath/work/SNIPER/symbols/faster/resnet_mx_101_e2e.py", line 335, in get_symbol_rcnn
    scales=tuple(cfg.network.ANCHOR_SCALES))
ValueError: need more than 1 value to unpack

**Comment by kouhinn** [comment]
@RajathSwaroop  I haven't run the original code from this github. Just implemented a new one based on the paper and have using some part of code from this github.

**Comment by bharatsingh430** [comment]
@kouhinn The code and default settings are modified and the scales are now defined based on image resolutions (in pixels) for easier tuning. At least on PASCAL VOC and COCO, the code works out-of-the-box with the default settings. Can you pull the master and check it again with the default parameters to see if the problem resolves?

**Comment by kouhinn** [comment]
OK. Thanks bharatsingh430. I'll pull and check.

**Comment by zoe218** [comment]
@kouhinn hello, I also want to apply sniper on my own dataset, but I got a worse performance. How's your performance now? And can I communicate with you about the implement of sniper? Thanks a lot~
