### ISSUE TITLE
Unable to run demo_3k.py

### ISSUE THREAD

**Issue by RajathSwaroop** [mahyarnajibi/SNIPER#75]
Traceback (most recent call last):
  File "demo_3k.py", line 21, in <module>
    from bbox.bbox_transform import bbox_pred, clip_boxes
  File "lib/bbox/bbox_transform.py", line 2, in <module>
    from bbox import bbox_overlaps_cython, ignore_overlaps_cython
ImportError: cannot import name bbox_overlaps_cython

This is the error I get after installing mxnet and other pre-requisites and running the demo_3k python executable.

**Comment by lishuchao012** [comment]
Met the same problem . Did you solve it ?

Traceback (most recent call last):
  File "demo.py", line 244, in <module>
    main()
  File "demo.py", line 52, in main
    sym = sym_inst.get_symbol_rcnn(config, is_train=False)
  File "/home/master/datas/deep-learning/sniper/cvpr3k/symbols/faster/resnet_mx_101_e2e_3k_demo.py", line 202, in get_symbol_rcnn
    rois, _ = mx.sym.MultiProposal(cls_prob=rpn_cls_prob_reshape, bbox_pred=rpn_bbox_pred, im_info=im_info,
AttributeError: 'module' object has no attribute 'MultiProposal'
