### ISSUE TITLE
Error running demo.py

### ISSUE THREAD

**Issue by RajathSwaroop** [mahyarnajibi/SNIPER#76]
AttributeError: 'module' object has no attribute 'MultiProposal'

This is the error i receive when I try running demo.py on the SNIPER github repo code

**Comment by RajathSwaroop** [comment]
Solved this error by running sudo python setup.py install in the python directory of SNIPER mxnet. However I get a new error trying to run the demo.py file that says:

Traceback (most recent call last):
  File "demo.py", line 118, in <module>
    main()
  File "demo.py", line 79, in main
    sym = sym_inst.get_symbol_rcnn(config, is_train=False)
  File "/home/rajath/work/SNIPER/symbols/faster/resnet_mx_101_e2e.py", line 335, in get_symbol_rcnn
    scales=tuple(cfg.network.ANCHOR_SCALES))
ValueError: need more than 1 value to unpack
