### ISSUE TITLE
Error running demo.py

### ISSUE THREAD

**Issue by JeasonUESTC** [mahyarnajibi/SNIPER#83]
It's a problem when i run demo.py.
Traceback (most recent call last):
  File "demo.py", line 16, in <module>
    from iterators.MNIteratorTest import MNIteratorTest
  File "lib/iterators/MNIteratorTest.py", line 3, in <module>
    from data_utils.data_workers import im_worker
  File "lib/data_utils/data_workers.py", line 10, in <module>
    from nms.nms import nms_wrapper
  File "lib/nms/nms.py", line 3, in <module>
    from cpu_nms import cpu_nms, cpu_soft_nms
ImportError: No module named cpu_nms
Who can give me a help? Thank you.

**Comment by chanajianyu** [comment]
you should use python 2.7 not python 3

**Comment by JeasonUESTC** [comment]
@chanajiany Thank you, the version of python is 2.7 and I have solve this problem.

**Comment by chanajianyu** [comment]
清水河兄弟，你跑demo时，直接成功了？
运行， python demo.py时，遇到core dump的报错没

**Comment by JeasonUESTC** [comment]
没，上面那个是因为没有编译C++file，你做过训练没有？

**Comment by JeasonUESTC** [comment]
> 清水河兄弟，你跑demo时，直接成功了？
> 运行， python demo.py时，遇到core dump的报错没

没，上面那个是因为没有编译C++file，你做过训练没有？

**Comment by JeasonUESTC** [comment]
@chanajianyu 作者编译的是SNIPER环境，我编译过了，原来训练用的是8块GPU，我想试试一块GPU跑通了的话训练自己数据集，在调试

**Comment by chanajianyu** [comment]
我记得在那里看的，作者提供的是一个修改后的mxnet版本

**Comment by JeasonUESTC** [comment]
按照Github里边的步骤来不就可以了?应该没什么问题吧

**Comment by JeasonUESTC** [comment]
@chanajianyu 按照Github里边的步骤来不就可以了?应该没什么问题吧

**Comment by chanajianyu** [comment]
然后，跑 demo.py时，会报错，core dump

**Comment by chanajianyu** [comment]
你有按照作者的步骤，编译 SNIPER-mxnet吗？

**Comment by JeasonUESTC** [comment]
我就是在哪找作者的过程compile，你这个是不是环境没有配置好。

**Comment by chanajianyu** [comment]
没啊，我cuda，cudnn，都ok的

**Comment by JeasonUESTC** [comment]
你之前要先配置编译mxnet环境吧

**Comment by JeasonUESTC** [comment]
@chanajianyu 搞定能不能不复现一下试试？

**Comment by JeasonUESTC** [comment]
@chanajianyu 你训练自己的数据集没有？

**Comment by MiraPurkrabek** [comment]
I got the same error while running python 3. When i run in python 2.7, I got error "No module named concurrent.features" from issue #85 . There is reccomendation to run in python 3. Any suggestions?

**Comment by zalach** [comment]
for me it was a problem with running compile.sh, it couldnt find the path to cuda lib64.
I changed the home path in SNIPER/lib/nms/setup_linux.py to point the cuda path ('/usr/local/cuda-9.2' for me) then run compile.sh.

**Comment by hhakko** [comment]
你好，我和你的报错是一样的，ImportError: No module named cpu_nms   我MXnet环境也配好了，C++文件也编译好了（编译时把.sh文件里面的python全部改为python3编译的），需要的包也安装好了，用的解释器是python3.5，单独运行nms.py不会报错，可是运行demo.py时，调用就会报错，请问问题出在哪里呢，感谢

**Comment by mosheliv** [comment]
got the same error, "illegal instruction (core dumped)". looks like it is related to cpu model (avx2?). anyone solved this? I am using the docker file and on my machine it core dumps but on other machine with more modern cpu it runs well.

**Comment by dd604** [comment]
> 你好，我和你的报错是一样的，ImportError: No module named cpu_nms 我MXnet环境也配好了，C++文件也编译好了（编译时把.sh文件里面的python全部改为python3编译的），需要的包也安装好了，用的解释器是python3.5，单独运行nms.py不会报错，可是运行demo.py时，调用就会报错，请问问题出在哪里呢，感谢

你好，冒昧麻烦你，请问这个问题你解决了吗？我现在用python3.6，编译好之后也是，ImportError: No module named cpu_nms这个问题，谢谢。

**Comment by hhakko** [comment]
你用python2就没问题了，&nbsp; python3 如何解决我也不清楚




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"dd604"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月8日(星期二) 下午4:41
收件人:&nbsp;"mahyarnajibi/SNIPER"<SNIPER@noreply.github.com&gt;;
抄送:&nbsp;"刘红燕"<571201542@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [mahyarnajibi/SNIPER] Error running demo.py (#83)



 
你好，我和你的报错是一样的，ImportError: No module named cpu_nms 我MXnet环境也配好了，C++文件也编译好了（编译时把.sh文件里面的python全部改为python3编译的），需要的包也安装好了，用的解释器是python3.5，单独运行nms.py不会报错，可是运行demo.py时，调用就会报错，请问问题出在哪里呢，感谢
  
你好，冒昧麻烦你，请问这个问题你解决了吗？我现在用python3.6，编译好之后也是，ImportError: No module named cpu_nms这个问题，谢谢。

**Comment by dd604** [comment]
@hhakko 谢谢你。我后来解决了，不过只是对inference部分进行了转换。用了一个python2转换成python3的库https://docs.python.org/3/library/2to3.html。转换之后，1）重新编译了一下nms的so，2）对转换到python3的代码，修改了几个相对路径，比如from .bbox.bbox_transform import bbox_pred, clip_boxes去掉了相对路径的点"."，改回原来的from bbox.bbox_transform import bbox_pred, clip_boxes。后来就可以再python3上使用了。这些贴出来，给后面需要的朋友。

**Comment by phamdat09** [comment]
Anyone can run this code with python3?
thanks

**Comment by hhakko** [comment]
I use python2





------------------ 原始邮件 ------------------
发件人:&nbsp;"phamdat09"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月20日(星期三) 晚上10:37
收件人:&nbsp;"mahyarnajibi/SNIPER"<SNIPER@noreply.github.com&gt;;
抄送:&nbsp;"刘红燕"<571201542@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [mahyarnajibi/SNIPER] Error running demo.py (#83)




Anyone can run this code with python3?
 thanks

**Comment by phamdat09** [comment]
> I use python2
> […](#)
> ------------------ 原始邮件 ------------------ 发件人:&nbsp;"phamdat09"<notifications@github.com&gt;; 发送时间:&nbsp;2019年11月20日(星期三) 晚上10:37 收件人:&nbsp;"mahyarnajibi/SNIPER"<SNIPER@noreply.github.com&gt;; 抄送:&nbsp;"刘红燕"<571201542@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; 主题:&nbsp;Re: [mahyarnajibi/SNIPER] Error running demo.py (#83) Anyone can run this code with python3? thanks — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

i already fixed it !!! I follow these guide of 'dd604' and it works
