### ISSUE TITLE
ImportError: No module named concurrent.futures

### ISSUE THREAD

**Issue by lichuang0529** [mahyarnajibi/SNIPER#85]
When I run the demo.py, I got the error:
Traceback (most recent call last):
  File "demo.py", line 16, in <module>
    from iterators.MNIteratorTest import MNIteratorTest
  File "lib/iterators/MNIteratorTest.py", line 4, in <module>
    from MNIteratorBase import MNIteratorBase
  File "lib/iterators/MNIteratorBase.py", line 4, in <module>
    from concurrent.futures import ThreadPoolExecutor
ImportError: No module named concurrent.futures
(SNIP) t1@t1:/media/t1/0a33a0a0-b876-45c1-bb1c-f0d
Could anyone help me?

**Comment by Laviyy** [comment]
@lichuang0529 Did you have solved it? I have the same problem.

**Comment by MiraPurkrabek** [comment]
I got the same error while running python 2.7. When i run in python 3, I got error "No module named cpu_nms" from issue #83 . There is recommendation to run in python 2.7. Any suggestions?

**Comment by captaincj** [comment]
in python2.7 pip install futures
