### ISSUE TITLE
Cannot find the MXNet library when run demo.py.

### ISSUE THREAD

**Issue by Laviyy** [mahyarnajibi/SNIPER#90]
weiliu@server:~/pycode/SNIPER$ python demo.py 
Traceback (most recent call last):
  File "demo.py", line 11, in <module>
    import mxnet as mx
  File "SNIPER-mxnet/python/mxnet/__init__.py", line 25, in <module>
    from . import engine
  File "SNIPER-mxnet/python/mxnet/engine.py", line 23, in <module>
    from .base import _LIB, check_call
  File "SNIPER-mxnet/python/mxnet/base.py", line 113, in <module>
    _LIB = _load_lib()
  File "SNIPER-mxnet/python/mxnet/base.py", line 104, in _load_lib
    lib_path = libinfo.find_lib_path()
  File "SNIPER-mxnet/python/mxnet/libinfo.py", line 71, in find_lib_path
    'List of candidates:\n' + str('\n'.join(dll_path)))
RuntimeError: Cannot find the MXNet library.
List of candidates:
/usr/local/cuda-9.0/lib64/libmxnet.so
/usr/local/cuda-9.0/lib64/libmxnet.so
/home/weiliu/pycode/SNIPER/SNIPER-mxnet/python/mxnet/libmxnet.so
/home/weiliu/pycode/SNIPER/SNIPER-mxnet/python/mxnet/../../lib/libmxnet.so
/home/weiliu/pycode/SNIPER/SNIPER-mxnet/python/mxnet/../../build/libmxnet.so
../../../libmxnet.so

**Comment by Souradip-sopho** [comment]
Hi, I am facing the same issue. Can you please share the details about how you resolved it?

**Comment by GeorgeSeif** [comment]
I'm also facing this issue. Were you able to solve this @Laviyy
