### ISSUE TITLE
AttributeError: 'module' object has no attribute 'MultiProposal'

### ISSUE THREAD

**Issue by leidaguo** [mahyarnajibi/SNIPER#92]
Traceback (most recent call last):
  File "demo.py", line 118, in <module>
    main()
  File "demo.py", line 79, in main
    sym = sym_inst.get_symbol_rcnn(config, is_train=False)
  File "/home/shaoyidu/Program/guoleida/detection/SNIPER/symbols/faster/resnet_mx_101_e2e.py", line 327, in get_symbol_rcnn
    rois, _ = mx.sym.MultiProposal(cls_prob=rpn_cls_prob_reshape, bbox_pred=rpn_bbox_pred, im_info=im_info,
AttributeError: 'module' object has no attribute 'MultiProposal'
How to solve it? Thanks

**Comment by bfialkoff** [comment]
Can we get some action here? I'm having the same issue.

**Comment by bfialkoff** [comment]
Did you manage to solve this?

**Comment by bharatsingh430** [comment]
You should be using the right mxnet repo which has that operator. Its implemented over https://github.com/mahyarnajibi/SNIPER-mxnet/blob/master/src/operator/multi_proposal.cu

**Comment by bfialkoff** [comment]
I am using that repo....How exactly should i be using a .cu file?

**Comment by wxianfeng** [comment]
init.py file add
`sys.path.insert(0,'SNIPER-mxnet/python')`

fixed

**Comment by hymanzhu1983** [comment]
It should be 
mx.sym.contrib.MultiProposal(cls_prob=rpn_cls_prob_reshape, bbox_pred=rpn_bbox_pred, im_info=im_info,
