### ISSUE TITLE
How to train with mobilenetv2

### ISSUE THREAD

**Issue by Hanson0910** [mahyarnajibi/SNIPER#95]
when train with mobilenetv2,the errors occurred as following:
Traceback (most recent call last):
  File "/home/fenghan/SNIPER/main_train.py", line 91, in <module>
    sym = sym_inst.get_symbol_rpn(config) if config.TRAIN.ONLY_PROPOSAL else sym_inst.get_symbol_rcnn(config)
  File "/home/fenghan/SNIPER/symbols/faster/mobilenetv2_e2e.py", line 254, in get_symbol_rcnn
    name='multi_proposal_target')
  File "<string>", line 107, in MultiProposalTarget
  File "SNIPER-mxnet/python/mxnet/_ctypes/symbol.py", line 135, in _symbol_creator
    s._compose(name=name, **kwargs)
  File "SNIPER-mxnet/python/mxnet/symbol/symbol.py", line 481, in _compose
    self.handle, name, num_args, keys, args))
  File "SNIPER-mxnet/python/mxnet/base.py", line 149, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [11:34:07] src/core/symbolic.cc:72: Symbol.ComposeKeyword argument name crowd_boxes not found.

**Comment by chituma110** [comment]
I had the same problem ,did you solved the problem? @Hanson0910

**Comment by Hanson0910** [comment]
I had solved the problem,i download the mobile-net pretrained model on ImageNet,and change the model paraments same as the code paraments。
| |
冯汉
|
|
superhan0910@163.com
|
签名由网易邮箱大师定制
On 4/2/2019 23:45，Qishang Cheng<notifications@github.com> wrote：

I had the same problem ,did you solved the problem? @Hanson0910

**Comment by Andrea-Chang** [comment]
hi @Hanson0910 ,
Would you kindly provide the modified pretrained model,
or could you give me some hint about how to modify the model parameters?
very thanks.

**Comment by Hanson0910** [comment]
You can download the pretrain model in 
https://github.com/chinakook/MobileNetV2.mxnet
签名由网易邮箱大师定制
On 5/4/2019 18:23，Andrea-Chang<notifications@github.com> wrote：

hi @Hanson0910 ,
Would you kindly provide the modified pretrained model,
or could you give me some hint about how to modify the model parameters?
very thanks.

**Comment by Andrea-Chang** [comment]
Hi @Hanson0910,
Thanks for your reply.
I downloaded the pre-trained model you provided above.
I am a mxnet newbie, could you kindly give me some hints about how to modify the "class MobilenetV2" in MobileNetV2.py to fit the code parameters?
Or should I do something else not just modify this file?

very thanks

**Comment by Hanson0910** [comment]
The xxx.params is a dictionary type data structure in python,you can modify the xxx.params's keys to fit the layer name in class MobilenetV2.


| |
冯汉
|
|
superhan0910@163.com
|
签名由网易邮箱大师定制
On 5/6/2019 11:56，Andrea-Chang<notifications@github.com> wrote：

Hi @Hanson0910,
Thanks for your reply.
I downloaded the pre-trained model you provided above.
I am a mxnet newbie, could you kindly give me some hints about how to modify the "class MobilenetV2" in MobileNetV2.py to fit the code parameters?
Or should I do something else not just modify this file?

very thanks

**Comment by Andrea-Chang** [comment]
Hi, @Hanson0910 ,
Thanks for you reply.
I load .params file and success get the dictionary.
Should I find related layer name in class MobilenetV2 or class mobilenetv2_e2e? 

Could you kindly show the example how to find the related layer name in class MobilenetV2(or mobilenetv2_e2e)?

For example:
the key in xxxx.params : 
arg:conv1_bn_beta 
arg:conv1_bn_gamma
arg:conv1_weight
arg:conv2_1_dwise_bn_beta
...
how can I find the related layer name in class MobilenetV2(or mobilenetv2_e2e)?

Thank you for your patience in answering all my questions.

**Comment by Hanson0910** [comment]
Give me your email,i send you the file.
On 5/5/2019 10:38，冯汉<superhan0910@163.com> wrote：


You can download the pretrain model in 
https://github.com/chinakook/MobileNetV2.mxnet
签名由网易邮箱大师定制
On 5/4/2019 18:23，Andrea-Chang<notifications@github.com> wrote：

hi @Hanson0910 ,
Would you kindly provide the modified pretrained model,
or could you give me some hint about how to modify the model parameters?
very thanks.

**Comment by Hanson0910** [comment]
Give me your email.i send you the file.
On 5/6/2019 16:17，Andrea-Chang<notifications@github.com> wrote：

Hi, @Hanson0910 ,
Thanks for you reply.
I load .params file and success get the dictionary.
Should I find related layer name in class MobilenetV2 or class mobilenetv2_e2e?

Could you kindly show the example how to find the related layer name in class MobilenetV2(or mobilenetv2_e2e)?

For example:
the key in xxxx.params :
arg:conv1_bn_beta
arg:conv1_bn_gamma
arg:conv1_weight
arg:conv2_1_dwise_bn_beta
...
how can I find the related layer name in class MobilenetV2(or mobilenetv2_e2e)?

Thank you for your patience in answering all my questions.

**Comment by Andrea-Chang** [comment]
hi, @Hanson0910,
My email: qbala1031@gmail.com

Thank you very much

**Comment by mehrdadazizi72** [comment]
@Hanson0910 can you send file for me?
mehrdad.azizi72@gmail.com
thanks in advanced

**Comment by yanliv** [comment]
I had the same problem, can you send file for me? 
yanli12321@qq.com
Thank you very much

**Comment by LP940708** [comment]
@Hanson0910 I had the same problem, can you send file for me?
1220755365@qq.com
Thank you very much

**Comment by czy1747** [comment]
@Hanson0910 I had the same problem, can you send file (mobilenetv2 and resnet50 pretained model) for me?
446115786@qq.com 
Thank you very much

**Comment by TianMingChen** [comment]
> Give me your email.i send you the file. On 5/6/2019 16:17，Andrea-Chang<notifications@github.com> wrote： Hi, @Hanson0910 , Thanks for you reply. I load .params file and success get the dictionary. Should I find related layer name in class MobilenetV2 or class mobilenetv2_e2e? Could you kindly show the example how to find the related layer name in class MobilenetV2(or mobilenetv2_e2e)? For example: the key in xxxx.params : arg:conv1_bn_beta arg:conv1_bn_gamma arg:conv1_weight arg:conv2_1_dwise_bn_beta ... how can I find the related layer name in class MobilenetV2(or mobilenetv2_e2e)? Thank you for your patience in answering all my questions. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

 I had the same problem, can you send file for me?
2561363477@qq.com
Thank you very much
